<#
.SYNOPSIS
    Set-HyperVDelegation-AllToAll.ps1
    Configures Kerberos delegation (RBCD or KCD) between ALL Hyper-V hosts so
    any host can live-migrate VMs to any other host.

.DESCRIPTION
    This is Step 1 of a two-step Kerberos live migration setup:

      Step 1 (THIS SCRIPT): Configure delegation trust in Active Directory
      Step 2 (Set-HyperVKerberosLiveMigration.ps1): Set each host's auth type to Kerberos

    Running Step 2 without Step 1 will BREAK live migration because the hosts
    will attempt Kerberos auth but no delegation trust exists in AD.

    This script is a "catch-all" -- it configures EVERY host to delegate to
    EVERY other host in the scope. This ensures live migration works in any
    direction without analyzing individual gaps first. For surgical gap-fixing
    based on the Hyper-V Inventory Report's KCD-Validation tab findings, use
    the per-host remediation scripts generated by the report instead (OPEN-61).

    TWO MODES
    ---------
    RBCD (default, recommended for Server 2012+):
      - Configures msDS-AllowedToActOnBehalfOfOtherIdentity on each DESTINATION host
      - The destination host controls who can delegate TO it
      - Does NOT require Domain Admin -- only requires write access to the
        destination host's AD computer object (Hyper-V Admins can do this)
      - Preferred approach per Microsoft documentation

    KCD (legacy, for pre-2012 or mixed environments):
      - Configures msDS-AllowedToDelegateTo on each SOURCE host
      - The source host's AD object lists which SPNs it can delegate TO
      - REQUIRES Domain Admin to modify the delegation properties
      - SPNs configured: cifs/<dest> and Microsoft Virtual System Migration Service/<dest>
        for both short name and FQDN of each destination

    WHAT THIS SCRIPT CONFIGURES
    ---------------------------
    For N hosts in scope, this script creates N*(N-1) delegation relationships
    (every host to every other host, bidirectional). For example:
      3 hosts (A, B, C) = 6 relationships: A->B, A->C, B->A, B->C, C->A, C->B

    The script is ADDITIVE -- it adds delegation entries without removing existing
    ones. Running it multiple times is safe (idempotent for RBCD; additive-safe
    for KCD since duplicate SPNs are harmless).

.PARAMETER Mode
    Delegation mode: 'RBCD' (default) or 'KCD'.
    RBCD is recommended for all Server 2012+ environments.

.PARAMETER ComputerName
    One or more Hyper-V host names or FQDNs.
    If omitted, auto-discovers from Active Directory using the same
    SPN-based detection as the Hyper-V Inventory Report (with CR110
    CNO/AG-listener filtering applied).

.PARAMETER ClusterName
    Optional: scope discovery to a single failover cluster.
    Uses Get-ClusterNode to enumerate only the nodes in that cluster.
    Mutually exclusive with -ComputerName.

.PARAMETER Credential
    PSCredential for AD operations. For RBCD, needs write access to
    destination host computer objects. For KCD, needs Domain Admin.
    If omitted, uses the current user context.

.PARAMETER Domain
    AD domain to query. Default: ohdc.com

.PARAMETER LogPath
    Directory for the change log CSV. Default: script directory.

.PARAMETER WhatIf
    Dry-run mode. Reports what WOULD be configured without making changes.

.PARAMETER Force
    Suppress confirmation prompts.

.EXAMPLE
    # Dry run -- see what would be configured (RBCD mode, all hosts)
    .\Set-HyperVDelegation-AllToAll.ps1 -WhatIf

.EXAMPLE
    # Configure RBCD for all hosts in the MHOHCLUHV cluster
    .\Set-HyperVDelegation-AllToAll.ps1 -ClusterName MHOHCLUHV -Force

.EXAMPLE
    # Configure KCD (legacy) for specific hosts
    .\Set-HyperVDelegation-AllToAll.ps1 -Mode KCD -ComputerName RICTX-HV-P01,RICTX-HV-P02 -Force

.EXAMPLE
    # Full environment RBCD configuration with credential prompt
    $cred = Get-Credential
    .\Set-HyperVDelegation-AllToAll.ps1 -Credential $cred -Force

.NOTES
    Author  : Michael George (with Claude)
    Version : 1.0.0
    Date    : 2026-04-21
    Related : Set-HyperVKerberosLiveMigration.ps1 (Step 2)
              OPEN-61 (report-driven per-host remediation scripts)
              OPEN-63 (this script)
    PS Compat: 5.1+
    Requires: ActiveDirectory module (RSAT-AD-PowerShell)
    Requires: FailoverClusters module if using -ClusterName
#>

#Requires -Version 5.1
#Requires -Modules ActiveDirectory

Function Set-HyperVDelegation-AllToAll
{

[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory = $false)]
    [ValidateSet('RBCD','KCD')]
    [string]$Mode = 'RBCD',

    [Parameter(Mandatory = $false, ParameterSetName = 'ByName')]
    [string[]]$ComputerName,

    [Parameter(Mandatory = $false, ParameterSetName = 'ByCluster')]
    [string]$ClusterName,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.PSCredential]$Credential,

    [Parameter(Mandatory = $false)]
    [string]$Domain = 'ohdc.com',

    [Parameter(Mandatory = $false)]
    [switch]$Force,

    [Parameter(Mandatory = $false)]
    [string]$LogPath = $PSScriptRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
$script:Version     = '1.0.0'
$script:ScriptName  = 'Set-HyperVDelegation-AllToAll'
$script:RunTime     = Get-Date -Format 'yyyyMMdd_HHmmss'
$script:LogFile     = Join-Path $LogPath "${script:ScriptName}_${script:RunTime}.csv"
$script:Results     = [System.Collections.Generic.List[PSCustomObject]]::new()

$script:ADParams = @{ Server = $Domain; ErrorAction = 'Stop' }
if ($Credential) { $script:ADParams['Credential'] = $Credential }

# KCD SPNs -- the two service classes needed for live migration
$script:MigrationSPNPrefixes = @(
    'cifs'
    'Microsoft Virtual System Migration Service'
)

# ---------------------------------------------------------------------------
# LOGGING
# ---------------------------------------------------------------------------
function Write-DLog {
    param(
        [string]$Message,
        [ValidateSet('Info','Success','Warning','Error','Change','DryRun')]
        [string]$Level = 'Info'
    )
    $ts = Get-Date -Format 'HH:mm:ss'
    $prefix = switch ($Level) {
        'Success' { '[OK]   ' }
        'Warning' { '[WARN] ' }
        'Error'   { '[ERR]  ' }
        'Change'  { '[CHG]  ' }
        'DryRun'  { '[DRY]  ' }
        default   { '[INF]  ' }
    }
    Write-Host "$ts $prefix $Message" -ForegroundColor $(switch ($Level) {
        'Success' { 'Green' }; 'Warning' { 'Yellow' }; 'Error' { 'Red' }
        'Change'  { 'Cyan' };  'DryRun'  { 'Magenta' }; default { 'White' }
    })
}

function Add-Result {
    param(
        [string]$Source,
        [string]$Destination,
        [string]$Action,
        [string]$Status,
        [string]$Detail
    )
    $script:Results.Add([PSCustomObject]@{
        Timestamp   = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        Mode        = $Mode
        Source       = $Source
        Destination = $Destination
        Action      = $Action
        Status      = $Status
        Detail      = $Detail
    })
}

# ---------------------------------------------------------------------------
# HOST DISCOVERY
# ---------------------------------------------------------------------------
function Get-TargetHosts {
    <#
    .SYNOPSIS
        Returns an array of AD computer objects for Hyper-V hosts in scope.
        Each object has Name, DNSHostName, and the full AD properties needed
        for delegation configuration.
    #>

    if ($ComputerName -and $ComputerName.Count -gt 0) {
        Write-DLog "Using $($ComputerName.Count) host(s) from -ComputerName parameter."
        $hosts = @()
        foreach ($cn in $ComputerName) {
            $shortName = ($cn -split '\.')[0]
            try {
                $adObj = Get-ADComputer -Identity $shortName @script:ADParams -Properties `
                    DNSHostName, ServicePrincipalName, OperatingSystem, `
                    msDS-AllowedToDelegateTo, PrincipalsAllowedToDelegateToAccount
                $hosts += $adObj
            }
            catch {
                Write-DLog "  Could not find AD computer object for '$cn': $($_.Exception.Message)" -Level Warning
            }
        }
        return $hosts
    }

    if ($ClusterName) {
        Write-DLog "Discovering nodes in cluster '$ClusterName'..."
        try {
            Import-Module FailoverClusters -ErrorAction Stop
            $clusterParams = @{ Name = $ClusterName; ErrorAction = 'Stop' }
            if ($Credential) { $clusterParams['Credential'] = $Credential }
            $nodes = Get-ClusterNode @clusterParams | Select-Object -ExpandProperty Name
            Write-DLog "  Found $($nodes.Count) nodes in cluster '$ClusterName'."
            $hosts = @()
            foreach ($n in $nodes) {
                try {
                    $adObj = Get-ADComputer -Identity $n @script:ADParams -Properties `
                        DNSHostName, ServicePrincipalName, OperatingSystem, `
                        msDS-AllowedToDelegateTo, PrincipalsAllowedToDelegateToAccount
                    $hosts += $adObj
                }
                catch {
                    Write-DLog "  Could not find AD object for cluster node '$n': $($_.Exception.Message)" -Level Warning
                }
            }
            return $hosts
        }
        catch {
            Write-DLog "Cluster discovery failed: $($_.Exception.Message)" -Level Error
            throw
        }
    }

    # Auto-discover from AD
    Write-DLog "Auto-discovering Hyper-V hosts from AD ($Domain)..."
    try {
        $allServers = Get-ADComputer -Filter { OperatingSystem -like '*Server*' } `
            @script:ADParams -Properties DNSHostName, ServicePrincipalName, OperatingSystem, `
            msDS-AllowedToDelegateTo, PrincipalsAllowedToDelegateToAccount

        $hosts = @()
        foreach ($comp in $allServers) {
            $spns = @($comp.ServicePrincipalName)
            $spnString = $spns -join ' '

            # CR110 guard: skip CNOs and AG listeners (no HOST/ or WSMAN/ SPN)
            $hasHostSPN  = $spnString -match '\bHOST/'
            $hasWsmanSPN = $spnString -match '\bWSMAN/'
            if (-not $hasHostSPN -and -not $hasWsmanSPN) {
                # Not a real server -- skip CNOs, AG listeners, SQL FCIs
                continue
            }

            # Hyper-V candidate check: must have Microsoft Virtual SPN or Hyper-V OS
            $isHVCandidate = ($spnString -match 'Microsoft Virtual') -or
                             ($comp.OperatingSystem -and $comp.OperatingSystem -match 'Hyper-V')
            if ($isHVCandidate) {
                $hosts += $comp
            }
        }

        Write-DLog "Found $($hosts.Count) Hyper-V host(s) in AD (after CR110 filtering)."
        return $hosts
    }
    catch {
        Write-DLog "AD discovery failed: $($_.Exception.Message)" -Level Error
        throw
    }
}

# ---------------------------------------------------------------------------
# PRE-FLIGHT REPORT -- show current delegation state
# ---------------------------------------------------------------------------
function Show-CurrentState {
    param([object[]]$Hosts)

    Write-DLog ''
    Write-DLog '--- CURRENT DELEGATION STATE ---'
    Write-DLog ''

    foreach ($h in $Hosts) {
        $name = $h.Name
        $existingKCD  = @($h.'msDS-AllowedToDelegateTo')
        $existingRBCD = @($h.PrincipalsAllowedToDelegateToAccount)

        $kcdCount  = if ($existingKCD  -and $existingKCD[0])  { $existingKCD.Count }  else { 0 }
        $rbcdCount = if ($existingRBCD -and $existingRBCD[0]) { $existingRBCD.Count } else { 0 }

        $detail = @()
        if ($kcdCount -gt 0)  { $detail += "KCD: $kcdCount SPN(s)" }
        if ($rbcdCount -gt 0) { $detail += "RBCD: $rbcdCount principal(s)" }
        if ($detail.Count -eq 0) { $detail = @('No delegation configured') }

        $color = if ($detail -contains 'No delegation configured') { 'Yellow' } else { 'Green' }
        Write-Host "  $($name.PadRight(25)) $($detail -join ' | ')" -ForegroundColor $color
    }
    Write-DLog ''
}

# ---------------------------------------------------------------------------
# RBCD CONFIGURATION
# ---------------------------------------------------------------------------
function Set-RBCDAllToAll {
    param([object[]]$Hosts, [bool]$IsDryRun)

    $total = $Hosts.Count
    $pairCount = $total * ($total - 1)
    Write-DLog "Configuring RBCD: $total hosts, $pairCount delegation relationships"
    Write-DLog ''

    foreach ($dest in $Hosts) {
        $destName = $dest.Name
        $otherHosts = @($Hosts | Where-Object { $_.Name -ne $destName })

        if ($otherHosts.Count -eq 0) {
            Write-DLog "  [$destName] Only one host in scope -- nothing to configure" -Level Warning
            continue
        }

        # Get current RBCD principals on this destination
        $currentPrincipals = @()
        try {
            $freshDest = Get-ADComputer -Identity $destName @script:ADParams -Properties PrincipalsAllowedToDelegateToAccount
            $currentPrincipals = @($freshDest.PrincipalsAllowedToDelegateToAccount)
        }
        catch {
            Write-DLog "  [$destName] Could not read current RBCD state: $($_.Exception.Message)" -Level Warning
        }

        # Build the new list: current principals + all other hosts
        $currentSIDs = @($currentPrincipals | ForEach-Object {
            if ($_) { $_.ToString() }
        })

        $newPrincipals = [System.Collections.Generic.List[object]]::new()
        # Keep existing principals
        foreach ($p in $currentPrincipals) {
            if ($p) { $newPrincipals.Add($p) }
        }

        $addedCount = 0
        foreach ($src in $otherHosts) {
            # Check if this source is already authorized
            $srcSID = $src.SID.ToString()
            $alreadyPresent = $currentSIDs -contains $srcSID

            if ($alreadyPresent) {
                Add-Result -Source $src.Name -Destination $destName -Action 'RBCD' -Status 'AlreadyConfigured' -Detail "Source $($src.Name) already in RBCD principals on $destName"
                continue
            }

            if ($IsDryRun) {
                Write-DLog "  [$destName] WOULD ADD: $($src.Name) to RBCD principals" -Level DryRun
                Add-Result -Source $src.Name -Destination $destName -Action 'RBCD' -Status 'WouldAdd' -Detail "Dry run"
                $addedCount++
            }
            else {
                $newPrincipals.Add($src)
                $addedCount++
                Add-Result -Source $src.Name -Destination $destName -Action 'RBCD' -Status 'Added' -Detail "Added $($src.Name) to RBCD principals on $destName"
            }
        }

        if ($addedCount -eq 0) {
            Write-DLog "  [$destName] All $($otherHosts.Count) sources already authorized (no changes needed)" -Level Success
            continue
        }

        if (-not $IsDryRun) {
            try {
                Set-ADComputer -Identity $destName @script:ADParams `
                    -PrincipalsAllowedToDelegateToAccount $newPrincipals.ToArray()
                Write-DLog "  [$destName] RBCD updated: added $addedCount source(s) (total: $($newPrincipals.Count) principals)" -Level Change
            }
            catch {
                Write-DLog "  [$destName] RBCD SET FAILED: $($_.Exception.Message)" -Level Error
                Add-Result -Source '(multiple)' -Destination $destName -Action 'RBCD' -Status 'FAILED' -Detail $_.Exception.Message
            }
        }
        else {
            Write-DLog "  [$destName] WOULD UPDATE RBCD with $addedCount new source(s)" -Level DryRun
        }
    }
}

# ---------------------------------------------------------------------------
# KCD CONFIGURATION
# ---------------------------------------------------------------------------
function Set-KCDAllToAll {
    param([object[]]$Hosts, [bool]$IsDryRun)

    $total = $Hosts.Count
    Write-DLog "Configuring KCD: $total hosts (requires Domain Admin)"
    Write-DLog ''

    foreach ($src in $Hosts) {
        $srcName = $src.Name
        $otherHosts = @($Hosts | Where-Object { $_.Name -ne $srcName })

        if ($otherHosts.Count -eq 0) {
            Write-DLog "  [$srcName] Only one host in scope -- nothing to configure" -Level Warning
            continue
        }

        # Get current KCD SPNs on this source
        $currentSPNs = @()
        try {
            $freshSrc = Get-ADComputer -Identity $srcName @script:ADParams -Properties 'msDS-AllowedToDelegateTo'
            $currentSPNs = @($freshSrc.'msDS-AllowedToDelegateTo')
        }
        catch {
            Write-DLog "  [$srcName] Could not read current KCD state: $($_.Exception.Message)" -Level Warning
        }

        # Build the list of SPNs needed
        $neededSPNs = [System.Collections.Generic.List[string]]::new()
        foreach ($dest in $otherHosts) {
            $destShort = $dest.Name
            $destFQDN  = $dest.DNSHostName
            foreach ($prefix in $script:MigrationSPNPrefixes) {
                $neededSPNs.Add("$prefix/$destShort")
                if ($destFQDN) {
                    $neededSPNs.Add("$prefix/$destFQDN")
                }
            }
        }

        # Find which SPNs are missing
        $missingSPNs = @($neededSPNs | Where-Object { $currentSPNs -notcontains $_ })

        if ($missingSPNs.Count -eq 0) {
            Write-DLog "  [$srcName] All $($neededSPNs.Count) delegation SPNs already configured (no changes needed)" -Level Success
            foreach ($dest in $otherHosts) {
                Add-Result -Source $srcName -Destination $dest.Name -Action 'KCD' -Status 'AlreadyConfigured' -Detail "All SPNs present"
            }
            continue
        }

        Write-DLog "  [$srcName] Missing $($missingSPNs.Count) of $($neededSPNs.Count) delegation SPNs"

        if ($IsDryRun) {
            foreach ($spn in $missingSPNs) {
                Write-DLog "    WOULD ADD: $spn" -Level DryRun
            }
            foreach ($dest in $otherHosts) {
                Add-Result -Source $srcName -Destination $dest.Name -Action 'KCD' -Status 'WouldAdd' -Detail "Dry run -- $($missingSPNs.Count) SPNs to add"
            }
        }
        else {
            try {
                # Add the missing SPNs to the existing list
                $allSPNs = @($currentSPNs) + $missingSPNs
                Set-ADComputer -Identity $srcName @script:ADParams `
                    -Replace @{ 'msDS-AllowedToDelegateTo' = $allSPNs }
                Write-DLog "  [$srcName] KCD updated: added $($missingSPNs.Count) SPN(s) (total: $($allSPNs.Count))" -Level Change
                foreach ($dest in $otherHosts) {
                    Add-Result -Source $srcName -Destination $dest.Name -Action 'KCD' -Status 'Added' -Detail "SPNs configured"
                }
            }
            catch {
                Write-DLog "  [$srcName] KCD SET FAILED: $($_.Exception.Message)" -Level Error
                Add-Result -Source $srcName -Destination '(all)' -Action 'KCD' -Status 'FAILED' -Detail $_.Exception.Message
            }
        }
    }
}

# ---------------------------------------------------------------------------
# VERIFICATION
# ---------------------------------------------------------------------------
function Test-DelegationState {
    param([object[]]$Hosts)

    Write-DLog ''
    Write-DLog '--- POST-CONFIGURATION VERIFICATION ---'
    Write-DLog ''

    $allGood = $true
    foreach ($h in $Hosts) {
        $name = $h.Name
        $otherCount = $Hosts.Count - 1

        try {
            $fresh = Get-ADComputer -Identity $name @script:ADParams -Properties `
                'msDS-AllowedToDelegateTo', PrincipalsAllowedToDelegateToAccount

            if ($Mode -eq 'RBCD') {
                $rbcdPrincipals = @($fresh.PrincipalsAllowedToDelegateToAccount)
                $rbcdCount = if ($rbcdPrincipals -and $rbcdPrincipals[0]) { $rbcdPrincipals.Count } else { 0 }

                if ($rbcdCount -ge $otherCount) {
                    Write-DLog "  [$name] RBCD: $rbcdCount principal(s) configured (need >= $otherCount) -- OK" -Level Success
                }
                else {
                    Write-DLog "  [$name] RBCD: $rbcdCount principal(s) configured (need >= $otherCount) -- INCOMPLETE" -Level Warning
                    $allGood = $false
                }
            }
            else {
                $kcdSPNs = @($fresh.'msDS-AllowedToDelegateTo')
                $kcdCount = if ($kcdSPNs -and $kcdSPNs[0]) { $kcdSPNs.Count } else { 0 }
                # Each destination needs 4 SPNs (cifs/short, cifs/fqdn, MigSvc/short, MigSvc/fqdn)
                $expectedMin = $otherCount * 4

                if ($kcdCount -ge $expectedMin) {
                    Write-DLog "  [$name] KCD: $kcdCount SPN(s) configured (need >= $expectedMin) -- OK" -Level Success
                }
                else {
                    Write-DLog "  [$name] KCD: $kcdCount SPN(s) configured (need >= $expectedMin) -- INCOMPLETE" -Level Warning
                    $allGood = $false
                }
            }
        }
        catch {
            Write-DLog "  [$name] Verification FAILED: $($_.Exception.Message)" -Level Error
            $allGood = $false
        }
    }

    return $allGood
}

# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------
Write-Host ''
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host "  $script:ScriptName  v$script:Version" -ForegroundColor Cyan
Write-Host "  Mode: $Mode" -ForegroundColor Cyan
Write-Host "  User: $(if ($Credential) { $Credential.UserName } else { "$env:USERDOMAIN\$env:USERNAME" })" -ForegroundColor Cyan
Write-Host "  Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
if ($WhatIfPreference) {
    Write-Host '  *** DRY RUN -- no changes will be made ***' -ForegroundColor Magenta
}
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host ''

# Step 1: Discover hosts
$hosts = Get-TargetHosts

if (-not $hosts -or $hosts.Count -eq 0) {
    Write-DLog "No Hyper-V hosts found. Nothing to configure." -Level Error
    return
}

if ($hosts.Count -eq 1) {
    Write-DLog "Only 1 host found ($($hosts[0].Name)). All-to-all delegation requires at least 2 hosts." -Level Warning
    return
}

Write-DLog "Hosts in scope: $($hosts.Count)"
foreach ($h in $hosts) {
    Write-DLog "  $($h.Name) ($($h.DNSHostName)) -- $($h.OperatingSystem)"
}

# Step 2: Show current state
Show-CurrentState -Hosts $hosts

# Step 3: Confirm
$pairCount = $hosts.Count * ($hosts.Count - 1)
if (-not $WhatIfPreference -and -not $Force) {
    Write-Host ''
    Write-Host "This will configure $Mode delegation for $($hosts.Count) hosts ($pairCount relationships)." -ForegroundColor Yellow
    Write-Host "Mode: $Mode" -ForegroundColor Yellow
    if ($Mode -eq 'KCD') {
        Write-Host "WARNING: KCD mode requires Domain Admin privileges." -ForegroundColor Red
    }
    $confirm = Read-Host "Continue? (Y/N)"
    if ($confirm -notmatch '^[Yy]') {
        Write-DLog "Aborted by user." -Level Warning
        return
    }
}

# Step 4: Configure
Write-DLog ''
Write-DLog "--- CONFIGURING $Mode DELEGATION ---"
Write-DLog ''

if ($Mode -eq 'RBCD') {
    Set-RBCDAllToAll -Hosts $hosts -IsDryRun $WhatIfPreference
}
else {
    Set-KCDAllToAll -Hosts $hosts -IsDryRun $WhatIfPreference
}

# Step 5: Verify (skip for dry run)
$verified = $false
if (-not $WhatIfPreference) {
    $verified = Test-DelegationState -Hosts $hosts
}

# Step 6: Export results
if ($script:Results.Count -gt 0) {
    try {
        $script:Results | Export-Csv -Path $script:LogFile -NoTypeInformation -Force
        Write-DLog "Change log written to: $script:LogFile"
    }
    catch {
        Write-DLog "Could not write log: $($_.Exception.Message)" -Level Warning
    }
}

# Step 7: Summary
Write-Host ''
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host '  SUMMARY' -ForegroundColor Cyan
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host "  Mode:          $Mode"
Write-Host "  Hosts:         $($hosts.Count)"
Write-Host "  Relationships: $pairCount"

$added   = @($script:Results | Where-Object { $_.Status -eq 'Added' }).Count
$already = @($script:Results | Where-Object { $_.Status -eq 'AlreadyConfigured' }).Count
$wouldAdd = @($script:Results | Where-Object { $_.Status -eq 'WouldAdd' }).Count
$failed  = @($script:Results | Where-Object { $_.Status -eq 'FAILED' }).Count

if ($WhatIfPreference) {
    Write-Host "  Would add:     $wouldAdd" -ForegroundColor Magenta
    Write-Host "  Already OK:    $already" -ForegroundColor Green
}
else {
    Write-Host "  Added:         $added" -ForegroundColor Cyan
    Write-Host "  Already OK:    $already" -ForegroundColor Green
    Write-Host "  Failed:        $failed" -ForegroundColor $(if ($failed -gt 0) { 'Red' } else { 'Green' })

    if ($verified) {
        Write-Host "  Verification:  PASSED" -ForegroundColor Green
    }
    else {
        Write-Host "  Verification:  INCOMPLETE (check warnings above)" -ForegroundColor Yellow
    }
}
Write-Host ''
if ($WhatIfPreference) {
    Write-Host '  DRY RUN -- no changes were made. Re-run without -WhatIf to apply.' -ForegroundColor Magenta
}
elseif ($failed -eq 0) {
    Write-Host '  Step 1 complete. Next:' -ForegroundColor Green
    Write-Host '  Run Set-HyperVKerberosLiveMigration.ps1 to set auth type (Step 2)' -ForegroundColor Green
}
else {
    Write-Host '  Some configurations failed. Review errors above and fix before Step 2.' -ForegroundColor Red
}
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host ''
}

