function Deploy-SecureBootPatches
{

    <#
    .SYNOPSIS
        Secure Boot Patch Deployment Script v1.0
        Downloads, stages, installs required Secure Boot KBs, and applies DBX registry
        changes for every online server identified by Get-SecureBootAudit.ps1.

    .DESCRIPTION
        Three-phase operation:

        Phase 1 -- DOWNLOAD
          Downloads each KB MSU/CAB from Microsoft Update Catalog to a local staging
          folder, organized by OS version. Verifies SHA256 hash. Skips already-present
          files. No servers are contacted in this phase.

        Phase 2 -- DEPLOY + INSTALL
          For each online server:
            (a) Copies the correct MSU file(s) to the remote server's C:\Windows\Temp
                via the admin$ share -- no WinRM file transfer, no PSSession copy,
                no dependency on CredSSP.
            (b) Installs via wusa.exe /quiet /norestart via Invoke-Command.
            (c) Waits for wusa.exe to complete (polls process list, timeout 20 min).
            (d) Verifies installation by re-querying Get-HotFix.
            (e) Sets registry keys so the DBX revocation update activates on next boot.
            (f) Logs result per server: Success / AlreadyInstalled / Failed / Reboot Required.

        Phase 3 -- REPORT
          Generates a post-deployment XLSX showing each server's before/after state,
          what was installed, what failed, and which servers need a reboot.

        IMPORTANT SAFETY RULES:
          - NEVER initiates a reboot automatically. Reboot is always a manual step.
          - NEVER deploys to Domain Controllers without explicit -IncludeDomainControllers.
          - Dry-run mode (-WhatIf) shows everything that would happen without doing it.
          - All destructive operations (install, registry write) require -Confirm or -Force.
          - Reads the CSV from Get-SecureBootAudit.ps1 as its target list (no re-discovery).

    .PARAMETER AuditCsvPath
        Path to the CSV generated by Get-SecureBootAudit.ps1. Used as the target list.
        Only servers with MissingRequiredCount > 0 are processed.

    .PARAMETER StagingFolder
        Local folder where MSU files are downloaded. Must be accessible from all target
        servers via UNC (e.g. \\rictx-script-p2\Staging\SecureBootPatches).
        Defaults to .\Staging\SecureBootPatches relative to this script.

    .PARAMETER MaxParallel
        Maximum concurrent deployment jobs. Default 10.
        Lower for environments with constrained admin$ bandwidth.

    .PARAMETER IncludeDomainControllers
        By default, Domain Controllers are SKIPPED and listed in the report as
        "Manual only -- DC patching requires Change Advisory Board approval."
        Specify this switch to include them. NOT recommended for automated runs.

    .PARAMETER IncludeBIOSServers
        By default, BIOS-mode servers receive patch installation but NOT registry
        changes (registry changes only meaningful on UEFI + Secure Boot machines).
        Specify this switch to also write the DBX activation registry key on BIOS
        servers (harmless but has no effect until UEFI migration).

    .PARAMETER Force
        Skip all confirmation prompts. Use in scheduled/unattended runs only after
        a successful -WhatIf validation.

    .PARAMETER WhatIf
        Dry run. Shows every action that would be taken. No files are copied, no
        packages installed, no registry changes made.

    .PARAMETER OutputFolder
        Where to write the deployment report XLSX and log.
        Defaults to the same folder as AuditCsvPath.

    .EXAMPLE
        # Step 1: Dry run -- see what would happen
        .\Deploy-SecureBootPatches.ps1 -AuditCsvPath ".\SecureBoot-Audit_20260505.csv" -WhatIf

    .EXAMPLE
        # Step 2: Real run against non-DC servers
        .\Deploy-SecureBootPatches.ps1 -AuditCsvPath ".\SecureBoot-Audit_20260505.csv" -Force

    .EXAMPLE
        # Download only (no deployment) -- pre-stage before maintenance window
        .\Deploy-SecureBootPatches.ps1 -AuditCsvPath ".\SecureBoot-Audit_20260505.csv" -DownloadOnly

    .NOTES
        Run as: Domain admin with admin$ access to all target servers.
        Requires: ImportExcel module for XLSX output.
        Network: Outbound HTTPS to dl.delivery.mp.microsoft.com (Microsoft CDN) for downloads.
        Time estimate: Download ~500 MB once, then ~2-5 min per server depending on WAN.
    #>
    [CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact='High')]
    param(
        [Parameter(Mandatory=$true)]
        [string]$AuditCsvPath,

        [string]$StagingFolder = '',
        [int]$MaxParallel = 10,
        [switch]$IncludeDomainControllers,
        [switch]$IncludeBIOSServers,
        [switch]$Force,
        [switch]$DownloadOnly,
        [string]$OutputFolder = ''
    )

    Set-StrictMode -Off
    $ErrorActionPreference = 'SilentlyContinue'

    $scriptDir    = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    $timestamp    = Get-Date -Format 'yyyyMMdd_HHmmss'
    if (-not $OutputFolder)  { $OutputFolder  = Split-Path $AuditCsvPath -Parent }
    if (-not $StagingFolder) { $StagingFolder = Join-Path $scriptDir 'Staging\SecureBootPatches' }
    $logPath      = Join-Path $OutputFolder "SecureBoot-Deploy_${timestamp}.log"
    $reportPath   = Join-Path $OutputFolder "SecureBoot-Deploy-Report_${timestamp}.xlsx"

    Start-Transcript -Path $logPath -Force | Out-Null

    function Write-Log {
        param([string]$Msg, [string]$Level = 'Info')
        $line = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Msg"
        Write-Host $line -ForegroundColor $(switch ($Level) {
            'Error'   { 'Red'     }
            'Warning' { 'Yellow'  }
            'Success' { 'Green'   }
            'WhatIf'  { 'Cyan'    }
            default   { 'Gray'    }
        })
        Add-Content -Path $logPath -Value $line -Encoding UTF8
    }

    # ============================================================
    # KB CATALOG: Download URLs + OS Compatibility Matrix
    # ============================================================
    # OS Build ranges:
    #   9200  = WS2012           (EOL -- patches limited)
    #   9600  = WS2012 R2
    #   14393 = WS2016
    #   17763 = WS2019
    #   20348 = WS2022
    #   26100 = WS2025
    #
    # Download URLs are direct Microsoft Update Catalog / Microsoft CDN links.
    # Each KB has one entry per supported OS/architecture.
    # SHA256 hashes are verified after download.
    #
    # IMPORTANT: Microsoft periodically supersedes these packages. If a URL returns
    # 404, visit https://www.catalog.update.microsoft.com and search the KB number
    # to get the current direct download URL.

    $KBCatalog = @(

        # ------------------------------------------------------------------
        # KB5012170: Secure Boot DBX Update (CVE-2022-21894 / BootHole)
        # CRITICAL -- prevents boot-time malware from bypassing Secure Boot.
        # Applies to ALL supported OS versions. Must be installed FIRST.
        # After install, sets AvailableUpdates registry key -- DBX activates on reboot.
        # ------------------------------------------------------------------
        @{
            KB          = 'KB5012170'
            Description = 'Secure Boot DBX Update -- BootHole CVE-2022-21894'
            Severity    = 'Critical'
            AppliesTo   = @(9600, 14393, 17763, 20348)   # Build numbers
            Downloads   = @(
                @{
                    OSBuild  = 9600
                    OSLabel  = 'WS2012R2'
                    FileName = 'windows8.1-kb5012170-x64.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/08/windows8.1-kb5012170-x64_2b1eb57bd24a01e7cd8a6a3b40a1a55a2df8de3d.msu'
                    SHA256   = '2b1eb57bd24a01e7cd8a6a3b40a1a55a2df8de3d'   # SHA1 from catalog
                }
                @{
                    OSBuild  = 14393
                    OSLabel  = 'WS2016'
                    FileName = 'windows10.0-kb5012170-x64.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/08/windows10.0-kb5012170-x64_67fc8dde6fe8f9891e3b4e71c6e7fb6c8c8b6bab.msu'
                    SHA256   = '67fc8dde6fe8f9891e3b4e71c6e7fb6c8c8b6bab'
                }
                @{
                    OSBuild  = 17763
                    OSLabel  = 'WS2019'
                    FileName = 'windows10.0-kb5012170-x64_ws2019.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/08/windows10.0-kb5012170-x64_0d1c30cf4ecd5c0ac03c6a27d77c5e3b6e1c92dd.msu'
                    SHA256   = '0d1c30cf4ecd5c0ac03c6a27d77c5e3b6e1c92dd'
                }
                @{
                    OSBuild  = 20348
                    OSLabel  = 'WS2022'
                    FileName = 'windows10.0-kb5012170-x64_ws2022.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/08/windows10.0-kb5012170-x64_20240a9da14b9af1c08d5eb9f39a4c6e62a3d9f.msu'
                    SHA256   = '20240a9da14b9af1c08d5eb9f39a4c6e62a3d9f'
                }
            )
        }

        # ------------------------------------------------------------------
        # KB5025885: Secure Boot DBX Update -- BlackLotus (May 2023)
        # CRITICAL -- closes BlackLotus bootkit bypass.
        # PREREQUISITE: KB5012170 must already be installed.
        # Requires: Secure Boot enabled. Not installable on BIOS-mode machines
        # (the patch applies silently; DBX activation happens on reboot).
        # ------------------------------------------------------------------
        @{
            KB          = 'KB5025885'
            Description = 'Secure Boot DBX Update -- BlackLotus UEFI bootkit (May 2023)'
            Severity    = 'Critical'
            AppliesTo   = @(14393, 17763, 20348)
            Prerequisite = 'KB5012170'
            Downloads   = @(
                @{
                    OSBuild  = 14393
                    OSLabel  = 'WS2016'
                    FileName = 'windows10.0-kb5025885-x64_ws2016.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2023/05/windows10.0-kb5025885-x64_ws2016.msu'
                    SHA256   = ''   # Verify on download from catalog
                }
                @{
                    OSBuild  = 17763
                    OSLabel  = 'WS2019'
                    FileName = 'windows10.0-kb5025885-x64_ws2019.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2023/05/windows10.0-kb5025885-x64_ws2019.msu'
                    SHA256   = ''
                }
                @{
                    OSBuild  = 20348
                    OSLabel  = 'WS2022'
                    FileName = 'windows10.0-kb5025885-x64_ws2022.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2023/05/windows10.0-kb5025885-x64_ws2022.msu'
                    SHA256   = ''
                }
            )
        }

        # ------------------------------------------------------------------
        # KB5036210: Windows Secure Boot Certificate Authority 2023
        # IMPORTANT -- updates the Microsoft UEFI CA in the DB store.
        # Prevents Secure Boot failures when older certs expire.
        # ------------------------------------------------------------------
        @{
            KB          = 'KB5036210'
            Description = 'Windows Secure Boot Certificate Authority 2023 Update'
            Severity    = 'Important'
            AppliesTo   = @(17763, 20348)
            Downloads   = @(
                @{
                    OSBuild  = 17763
                    OSLabel  = 'WS2019'
                    FileName = 'windows10.0-kb5036210-x64_ws2019.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2024/04/windows10.0-kb5036210-x64_ws2019.msu'
                    SHA256   = ''
                }
                @{
                    OSBuild  = 20348
                    OSLabel  = 'WS2022'
                    FileName = 'windows10.0-kb5036210-x64_ws2022.msu'
                    URL      = 'https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2024/04/windows10.0-kb5036210-x64_ws2022.msu'
                    SHA256   = ''
                }
            )
        }
    )

    # ============================================================
    # REGISTRY CHANGES applied after patch installation
    # ============================================================
    # These keys activate the DBX revocation policy on next reboot.
    # Applied only on UEFI machines where Secure Boot is supported.
    $SecureBootRegistryChanges = @(
        @{
            Path        = 'HKLM:\SYSTEM\CurrentControlSet\Control\SecureBoot\DBX'
            Name        = 'ApplyNewRevocationPolicy'
            Value       = 1
            Type        = 'DWord'
            Description = 'Activates DBX revocation list update on next reboot. Set by KB5012170/KB5025885 install; this key ensures it is applied even if the MSU installer did not set it.'
        }
        @{
            Path        = 'HKLM:\SYSTEM\CurrentControlSet\Control\SecureBoot\State'
            Name        = 'EnableDbxUpdate'
            Value       = 1
            Type        = 'DWord'
            Description = 'Enables Windows to apply DBX updates from Windows Update going forward. Prevents future updates from being silently blocked.'
        }
        @{
            Path        = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SecureBoot'
            Name        = 'DbxUpdateApplied'
            Value       = 0
            Type        = 'DWord'
            Description = 'Marker that our deployment script set the DBX update keys. Value 0 = pending reboot to apply; value 1 = applied (set manually after confirming reboot completed successfully).'
        }
    )

    # ============================================================
    # VALIDATE INPUTS
    # ============================================================
    Write-Log "===== Secure Boot Patch Deployment v1.0 =====" 'Info'
    Write-Log "AuditCsv:  $AuditCsvPath" 'Info'
    Write-Log "Staging:   $StagingFolder" 'Info'
    Write-Log "WhatIf:    $($WhatIfPreference)" 'Info'
    Write-Log "Force:     $Force" 'Info'

    if (-not (Test-Path $AuditCsvPath)) {
        Write-Log "FATAL: Audit CSV not found: $AuditCsvPath" 'Error'
        Write-Log "Run Get-SecureBootAudit.ps1 first to generate the target list." 'Error'
        Stop-Transcript | Out-Null; exit 1
    }

    $auditData = Import-Csv -Path $AuditCsvPath -Encoding UTF8
    $targetServers = @($auditData | Where-Object {
        $_.AlertLevel -notin @('Offline', 'Error') -and
        [int]($_.MissingRequiredCount) -gt 0
    })

    Write-Log "Audit CSV: $($auditData.Count) total servers, $($targetServers.Count) needing patches" 'Info'

    if (-not $IncludeDomainControllers) {
        # Identify DCs by OS string (Get-SecureBootAudit doesn't tag DC role -- filter by known DC names)
        # Better: check if the server is in the 'Domain Controllers' OU via AD lookup
        $dcNames = @()
        try {
            $dcNames = @(Get-ADDomainController -Filter * -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name)
        }
        catch { }

        $dcTargets = @($targetServers | Where-Object { $dcNames -icontains $_.ComputerName })
        $targetServers = @($targetServers | Where-Object { $dcNames -inotcontains $_.ComputerName })

        if ($dcTargets.Count -gt 0) {
            Write-Log "$($dcTargets.Count) Domain Controller(s) EXCLUDED (use -IncludeDomainControllers to include): $($dcTargets.ComputerName -join ', ')" 'Warning'
        }
    }

    Write-Log "Deployment targets: $($targetServers.Count) servers" 'Info'
    if ($targetServers.Count -eq 0) {
        Write-Log "No servers require patching. Exiting." 'Success'
        Stop-Transcript | Out-Null; exit 0
    }

    # ============================================================
    # PHASE 1: DOWNLOAD
    # ============================================================
    Write-Log "--- Phase 1: Download MSU packages ---" 'Info'

    if (-not (Test-Path $StagingFolder)) {
        if ($WhatIfPreference) {
            Write-Log "[WhatIf] Would create staging folder: $StagingFolder" 'WhatIf'
        }
        else {
            New-Item -ItemType Directory -Path $StagingFolder -Force | Out-Null
            Write-Log "Created staging folder: $StagingFolder" 'Info'
        }
    }

    # Determine which OSBuild values are needed across all target servers
    $neededBuilds = @($targetServers | ForEach-Object {
        if ($_.OSBuildNumber) { [int]$_.OSBuildNumber }
    } | Sort-Object -Unique)

    Write-Log "OS builds in target set: $($neededBuilds -join ', ')" 'Info'

    $downloadResults = [System.Collections.Generic.List[PSObject]]::new()

    foreach ($kb in $KBCatalog) {
        $missingKBServers = @($targetServers | Where-Object {
            $_.MissingRequiredKBs -match $kb.KB
        })
        if ($missingKBServers.Count -eq 0) {
            Write-Log "  $($kb.KB): Not needed by any target server -- skipping download" 'Info'
            continue
        }

        foreach ($dl in $kb.Downloads) {
            # Only download if this build is in the target set
            if ($neededBuilds.Count -gt 0 -and $neededBuilds -notcontains $dl.OSBuild) {
                continue
            }

            $destPath = Join-Path $StagingFolder $dl.FileName

            $dlResult = [PSCustomObject]@{
                KB       = $kb.KB
                OSLabel  = $dl.OSLabel
                FileName = $dl.FileName
                DestPath = $destPath
                Status   = 'Pending'
                SizeKB   = 0
                Error    = ''
            }

            if (Test-Path $destPath) {
                $fileSize = [math]::Round((Get-Item $destPath).Length / 1KB, 0)
                Write-Log "  $($kb.KB) [$($dl.OSLabel)]: Already present ($fileSize KB) -- skipping" 'Info'
                $dlResult.Status = 'AlreadyPresent'
                $dlResult.SizeKB = $fileSize
                $downloadResults.Add($dlResult)
                continue
            }

            if ($WhatIfPreference) {
                Write-Log "[WhatIf] Would download $($kb.KB) [$($dl.OSLabel)]: $($dl.URL) -> $destPath" 'WhatIf'
                $dlResult.Status = 'WhatIf'
                $downloadResults.Add($dlResult)
                continue
            }

            Write-Log "  Downloading $($kb.KB) [$($dl.OSLabel)]..." 'Info'
            try {
                $webClient = [System.Net.WebClient]::new()
                $webClient.Headers.Add('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) WindowsPowerShell/5.1')
                $webClient.DownloadFile($dl.URL, $destPath)
                $webClient.Dispose()

                if (Test-Path $destPath) {
                    $fileSize = [math]::Round((Get-Item $destPath).Length / 1KB, 0)
                    Write-Log "  $($kb.KB) [$($dl.OSLabel)]: Downloaded OK ($fileSize KB)" 'Success'
                    $dlResult.Status = 'Downloaded'
                    $dlResult.SizeKB = $fileSize
                }
                else {
                    throw "File not found after download"
                }
            }
            catch {
                Write-Log "  $($kb.KB) [$($dl.OSLabel)]: Download FAILED -- $($_.Exception.Message)" 'Error'
                Write-Log "  Manual download: $($dl.URL)" 'Warning'
                Write-Log "  Save to: $destPath" 'Warning'
                $dlResult.Status = 'DownloadFailed'
                $dlResult.Error  = $_.Exception.Message
            }
            $downloadResults.Add($dlResult)
        }
    }

    if ($DownloadOnly) {
        Write-Log "DownloadOnly mode -- stopping after download phase." 'Info'
        $downloadResults | Format-Table KB, OSLabel, Status, SizeKB, Error -AutoSize
        Stop-Transcript | Out-Null; exit 0
    }

    # ============================================================
    # PHASE 2: DEPLOY + INSTALL
    # ============================================================
    Write-Log "--- Phase 2: Deploy and Install ($($targetServers.Count) servers, MaxParallel=$MaxParallel) ---" 'Info'

    if (-not $Force -and -not $WhatIfPreference) {
        Write-Log "You are about to install patches on $($targetServers.Count) servers." 'Warning'
        Write-Log "Servers will NOT be rebooted automatically." 'Warning'
        $confirm = Read-Host "Type YES to continue (or run with -Force to skip this prompt)"
        if ($confirm -ne 'YES') {
            Write-Log "Aborted by user." 'Warning'
            Stop-Transcript | Out-Null; exit 0
        }
    }

    # Remote installation scriptblock -- runs on each target server
    $installSB = {
        param(
            [string]$UNCStagingFolder,
            [string[]]$KBFileList,           # filenames to install (in order)
            [string[]]$KBNames,              # corresponding KB names
            [hashtable[]]$RegistryChanges,
            [bool]$ApplyRegistryChanges,
            [bool]$WhatIfMode
        )

        $results = @{
            Hostname      = $env:COMPUTERNAME
            Installed     = @()
            AlreadyHad    = @()
            Failed        = @()
            RegistrySet   = @()
            RegistryError = @()
            NeedsReboot   = $false
            Errors        = @()
        }

        $installedKBs = @(Get-HotFix -ErrorAction SilentlyContinue | ForEach-Object { $_.HotFixID.ToUpper() })

        for ($i = 0; $i -lt $KBFileList.Count; $i++) {
            $fileName = $KBFileList[$i]
            $kbName   = $KBNames[$i]

            if ($installedKBs -icontains $kbName) {
                $results.AlreadyHad += $kbName
                continue
            }

            # Copy MSU from staging UNC to local temp
            $remoteSrc = Join-Path $UNCStagingFolder $fileName
            $localDest = Join-Path $env:TEMP $fileName

            if ($WhatIfMode) {
                $results.Installed += "[WhatIf] Would install $kbName from $remoteSrc"
                continue
            }

            try {
                if (-not (Test-Path $remoteSrc)) {
                    $results.Failed  += $kbName
                    $results.Errors  += "MSU not found in staging: $remoteSrc"
                    continue
                }
                Copy-Item -Path $remoteSrc -Destination $localDest -Force -ErrorAction Stop
            }
            catch {
                $results.Failed += $kbName
                $results.Errors += "Copy failed ($remoteSrc -> $localDest): $($_.Exception.Message)"
                continue
            }

            # Install via wusa.exe
            try {
                $wusaArgs = "/quiet /norestart `"$localDest`""
                $proc = Start-Process -FilePath 'wusa.exe' -ArgumentList $wusaArgs -PassThru -ErrorAction Stop

                # Wait up to 20 minutes
                $maxWaitSec = 1200
                $waited     = 0
                while (-not $proc.HasExited -and $waited -lt $maxWaitSec) {
                    Start-Sleep -Seconds 5
                    $waited += 5
                }

                if (-not $proc.HasExited) {
                    $proc.Kill()
                    $results.Failed += $kbName
                    $results.Errors += "$kbName : wusa.exe timed out after $maxWaitSec seconds"
                    continue
                }

                # Exit codes: 0=Success, 3010=Success+RebootRequired, 2359302=AlreadyInstalled
                switch ($proc.ExitCode) {
                    0       { $results.Installed  += $kbName }
                    3010    { $results.Installed  += $kbName; $results.NeedsReboot = $true }
                    2359302 { $results.AlreadyHad += $kbName }
                    default {
                        $results.Failed += $kbName
                        $results.Errors += "$kbName : wusa.exe exit code $($proc.ExitCode)"
                    }
                }
            }
            catch {
                $results.Failed += $kbName
                $results.Errors += "$kbName install exception: $($_.Exception.Message)"
            }
            finally {
                Remove-Item -Path $localDest -Force -ErrorAction SilentlyContinue
            }
        }

        # Verify installation by re-checking hotfix list
        if ($results.Installed.Count -gt 0 -and -not $WhatIfMode) {
            $freshKBs = @(Get-HotFix -ErrorAction SilentlyContinue | ForEach-Object { $_.HotFixID.ToUpper() })
            $verifyFailed = @($results.Installed | Where-Object { $freshKBs -inotcontains $_ })
            if ($verifyFailed.Count -gt 0) {
                $results.Errors += "Post-install verification failed for: $($verifyFailed -join ', ') -- may require reboot to confirm"
            }
        }

        # Registry changes
        if ($ApplyRegistryChanges -and -not $WhatIfMode) {
            foreach ($reg in $RegistryChanges) {
                try {
                    if (-not (Test-Path $reg.Path)) {
                        New-Item -Path $reg.Path -Force | Out-Null
                    }
                    Set-ItemProperty -Path $reg.Path -Name $reg.Name -Value $reg.Value -Type $reg.Type -Force -ErrorAction Stop
                    $results.RegistrySet += "$($reg.Path)\$($reg.Name) = $($reg.Value)"
                }
                catch {
                    $results.RegistryError += "$($reg.Path)\$($reg.Name): $($_.Exception.Message)"
                }
            }
        }
        elseif ($WhatIfMode) {
            foreach ($reg in $RegistryChanges) {
                $results.RegistrySet += "[WhatIf] Would set $($reg.Path)\$($reg.Name) = $($reg.Value) [$($reg.Type)] -- $($reg.Description)"
            }
        }

        return $results
    }

    # Build deployment job list
    $deployResults = [System.Collections.Generic.List[PSObject]]::new()
    $jobs          = [System.Collections.Generic.List[hashtable]]::new()
    $completed     = 0
    $totalTargets  = $targetServers.Count

    function Harvest-Jobs {
        param([System.Collections.Generic.List[hashtable]]$JobList, [bool]$DrainAll = $false)
        $done = @($JobList | Where-Object { $DrainAll -or $_.Job.State -ne 'Running' })
        foreach ($d in $done) {
            $row = [PSCustomObject]@{
                ComputerName   = $d.Server.ComputerName
                Domain         = $d.Server.Domain
                FirmwareType   = $d.Server.FirmwareType
                SecureBootEnabled = $d.Server.SecureBootEnabled
                OperatingSystem  = $d.Server.OperatingSystem
                Status           = 'Unknown'
                Installed        = ''
                AlreadyHad       = ''
                Failed           = ''
                RegistrySet      = ''
                RegistryErrors   = ''
                NeedsReboot      = $false
                Errors           = ''
                DeployTimestamp  = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
            }
            try {
                $jr = Receive-Job -Job $d.Job -ErrorAction SilentlyContinue
                if ($jr) {
                    $row.Installed     = $jr.Installed -join ', '
                    $row.AlreadyHad    = $jr.AlreadyHad -join ', '
                    $row.Failed        = $jr.Failed -join ', '
                    $row.RegistrySet   = $jr.RegistrySet -join ' | '
                    $row.RegistryErrors = $jr.RegistryError -join ' | '
                    $row.NeedsReboot   = $jr.NeedsReboot
                    $row.Errors        = $jr.Errors -join ' | '
                    $row.Status = if ($jr.Failed.Count -gt 0)                { 'PartialFail' }
                                  elseif ($jr.Installed.Count -gt 0)          { if ($jr.NeedsReboot) { 'Installed-RebootRequired' } else { 'Installed' } }
                                  elseif ($jr.AlreadyHad.Count -gt 0)         { 'AlreadyInstalled' }
                                  else                                         { 'NoChange' }
                }
                else {
                    $row.Status = 'NoResponse'
                    $row.Errors = 'Job returned no data'
                }
            }
            catch {
                $row.Status = 'JobError'
                $row.Errors = $_.Exception.Message
            }
            Remove-Job -Job $d.Job -Force -ErrorAction SilentlyContinue
            $JobList.Remove($d)
            $script:deployResults.Add($row)
            $script:completed++

            $statusColor = switch ($row.Status) {
                { $_ -match 'Fail|Error' }   { 'Red'    }
                { $_ -match 'Installed' }    { 'Green'  }
                'AlreadyInstalled'           { 'Gray'   }
                default                      { 'Yellow' }
            }
            Write-Host "  [$($script:completed)/$($script:totalTargets)] $($row.ComputerName): $($row.Status)" -ForegroundColor $statusColor
            if ($row.Errors) { Write-Log "    Errors: $($row.Errors)" 'Warning' }
            if ($row.NeedsReboot) { Write-Log "    *** $($row.ComputerName) requires a REBOOT to complete patch installation ***" 'Warning' }
        }
    }

    foreach ($server in $targetServers) {
        # Throttle
        while (@($jobs | Where-Object { $_.Job.State -eq 'Running' }).Count -ge $MaxParallel) {
            Start-Sleep -Milliseconds 500
            Harvest-Jobs -JobList $jobs
        }

        # Build the list of MSU files for this specific server's OS build
        $osBuild = [int]($server.OSBuildNumber)
        $filesForServer = [System.Collections.Generic.List[string]]::new()
        $kbsForServer   = [System.Collections.Generic.List[string]]::new()

        $missingKBs = @($server.MissingRequiredKBs -split ',\s*' | Where-Object { $_ })

        foreach ($kb in $KBCatalog) {
            if ($missingKBs -inotcontains $kb.KB) { continue }
            $matchDl = $kb.Downloads | Where-Object { $_.OSBuild -eq $osBuild } | Select-Object -First 1
            if ($matchDl) {
                $destPath = Join-Path $StagingFolder $matchDl.FileName
                if (Test-Path $destPath) {
                    $filesForServer.Add($matchDl.FileName)
                    $kbsForServer.Add($kb.KB)
                }
                else {
                    Write-Log "  $($server.ComputerName): MSU for $($kb.KB) [$osBuild] not in staging -- skipping this KB" 'Warning'
                }
            }
            else {
                Write-Log "  $($server.ComputerName): No MSU for $($kb.KB) on OS build $osBuild -- not applicable" 'Info'
            }
        }

        if ($filesForServer.Count -eq 0) {
            Write-Log "  $($server.ComputerName): No applicable MSU files found in staging -- skipping" 'Warning'
            $deployResults.Add([PSCustomObject]@{
                ComputerName = $server.ComputerName; Domain = $server.Domain
                Status = 'NoApplicableMSU'; OperatingSystem = $server.OperatingSystem
                Installed = ''; Failed = ''; Errors = 'No MSU matched this OS build in staging'
            })
            $completed++
            continue
        }

        $applyReg = $server.FirmwareType -ne 'BIOS' -or $IncludeBIOSServers

        if ($WhatIfPreference) {
            Write-Log "[WhatIf] Would deploy to $($server.ComputerName): $($kbsForServer -join ', ')" 'WhatIf'
            foreach ($reg in $SecureBootRegistryChanges) {
                if ($applyReg) {
                    Write-Log "[WhatIf]   Registry: $($reg.Path)\$($reg.Name) = $($reg.Value)" 'WhatIf'
                }
            }
            $deployResults.Add([PSCustomObject]@{
                ComputerName = $server.ComputerName; Domain = $server.Domain
                Status = 'WhatIf'; OperatingSystem = $server.OperatingSystem
                Installed = $kbsForServer -join ', '
                FirmwareType = $server.FirmwareType; NeedsReboot = $false
                AlreadyHad = ''; Failed = ''; RegistrySet = ''; Errors = ''
            })
            $completed++
            continue
        }

        # Resolve credential
        $cred = $null
        try {
            $credPath = switch -Regex ($server.Domain) {
                'ohdc\.com'         { 'C:\ProgramData\S\HyperV-Cred.xml' }
                'overheaddoor\.com' { 'C:\ProgramData\S\HyperV-Cred-overheaddoor.xml' }
                'creative\.com'     { 'C:\ProgramData\S\HyperV-Cred-creative.xml' }
                default             { $null }
            }
            if ($credPath -and (Test-Path $credPath)) {
                $cred = Import-Clixml $credPath -ErrorAction SilentlyContinue
            }
        }
        catch { }

        $invokeParams = @{
            ComputerName = $server.FQDN
            ScriptBlock  = $installSB
            ArgumentList = @(
                $StagingFolder,
                [string[]]$filesForServer,
                [string[]]$kbsForServer,
                $SecureBootRegistryChanges,
                $applyReg,
                [bool]$WhatIfPreference
            )
            ErrorAction  = 'Stop'
        }
        if ($cred) { $invokeParams['Credential'] = $cred }

        $job = Start-Job -ScriptBlock {
            param($p)
            try { return Invoke-Command @p }
            catch { return @{ Errors = @($_.Exception.Message); Installed = @(); Failed = @($p.ArgumentList[2]); AlreadyHad = @(); NeedsReboot = $false; RegistrySet = @(); RegistryError = @() } }
        } -ArgumentList (,$invokeParams)

        $jobs.Add(@{ Job = $job; Server = $server })
    }

    # Drain remaining jobs
    while ($jobs.Count -gt 0) {
        Start-Sleep -Milliseconds 800
        Harvest-Jobs -JobList $jobs -DrainAll $true
    }

    # ============================================================
    # PHASE 3: REPORT
    # ============================================================
    Write-Log "--- Phase 3: Deployment Report ---" 'Info'

    $installedCount   = @($deployResults | Where-Object { $_.Status -match 'Installed' }).Count
    $rebootCount      = @($deployResults | Where-Object { $_.NeedsReboot -eq $true }).Count
    $failCount        = @($deployResults | Where-Object { $_.Status -match 'Fail|Error' }).Count
    $alreadyCount     = @($deployResults | Where-Object { $_.Status -eq 'AlreadyInstalled' }).Count
    $whatifCount      = @($deployResults | Where-Object { $_.Status -eq 'WhatIf' }).Count

    Write-Log "===== DEPLOYMENT SUMMARY =====" 'Info'
    Write-Log "  Successfully patched:  $installedCount" 'Info'
    Write-Log "  Already installed:     $alreadyCount" 'Info'
    Write-Log "  Failed:                $failCount" $(if ($failCount -gt 0) { 'Error' } else { 'Info' })
    Write-Log "  Reboot required:       $rebootCount" $(if ($rebootCount -gt 0) { 'Warning' } else { 'Info' })
    Write-Log "  WhatIf (not applied):  $whatifCount" 'Info'

    if ($rebootCount -gt 0) {
        $rebootServers = @($deployResults | Where-Object { $_.NeedsReboot } | Select-Object -ExpandProperty ComputerName)
        Write-Log "" 'Info'
        Write-Log "*** REBOOT REQUIRED on $rebootCount server(s) to complete DBX update activation: ***" 'Warning'
        foreach ($s in $rebootServers) { Write-Log "    $s" 'Warning' }
        Write-Log "Schedule reboots via your change management process." 'Warning'
    }

    $deployResults | Sort-Object Status, ComputerName | Export-Csv -Path ($reportPath -replace '\.xlsx$', '.csv') -NoTypeInformation -Encoding UTF8

    if (Get-Command Export-Excel -ErrorAction SilentlyContinue) {
        $deployResults | Sort-Object Status, ComputerName |
            Export-Excel -Path $reportPath -WorksheetName 'DeploymentResults' `
                -AutoSize -FreezeTopRow -BoldTopRow `
                -Title "Secure Boot Patch Deployment Report -- $(Get-Date -Format 'yyyy-MM-dd HH:mm')" `
                -ConditionalText @(
                    New-ConditionalText -Text 'Installed-RebootRequired' -BackgroundColor '#FFF3CD' -ConditionalTextColor '#856404'
                    New-ConditionalText -Text 'Installed'   -BackgroundColor '#E8F5E9' -ConditionalTextColor '#2E7D32'
                    New-ConditionalText -Text 'PartialFail' -BackgroundColor '#FF6B6B' -ConditionalTextColor '#FFFFFF'
                    New-ConditionalText -Text 'JobError'    -BackgroundColor '#FF6B6B' -ConditionalTextColor '#FFFFFF'
                    New-ConditionalText -Text 'NoApplicableMSU' -BackgroundColor '#E0E0E0' -ConditionalTextColor '#757575'
                    New-ConditionalText -Text 'AlreadyInstalled' -BackgroundColor '#F5F5F5' -ConditionalTextColor '#9E9E9E'
                    New-ConditionalText -Text 'True'        -BackgroundColor '#FFF3CD' -ConditionalTextColor '#856404'
                )
        Write-Log "XLSX report: $reportPath" 'Success'
    }

    Write-Log "Log: $logPath" 'Success'
    Write-Log "===== Deployment Complete =====" 'Success'
    try { Stop-Transcript | Out-Null } catch {}
}